name: Run Build

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@v4

    - name: (Z) Install Zig
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master

    - name: ▶️ Validate Build
      shell: bash
      run: zig build
