name: Run Build (Ubuntu)

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/**
      - build/**
      - include/**
      - build.zig
      - build.zig.zon

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: (Z) Install Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.15.0-dev.565+8e72a2528

    - name: Validate Build
      shell: bash
      run: zig build
